version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint
    versions:
    - 2.7.0
    - 2.7.1
    - 2.7.3
    - 2.7.4
    - 2.8.1
  - dependency-name: astroid
    versions:
    - 2.5.3
  - dependency-name: django
    versions:
    - 3.1.7
  - dependency-name: defusedxml
    versions:
    - 0.7.0
  - dependency-name: pillow
    versions:
    - 8.1.1
